version: '3.9'
services:
  server1:
    build: ./server1
    ports:
      - "5000:5000"  # Expose port 5000 on localhost

  server2:
    build: ./server2
    ports:
      - "6000:6000"  # Expose port 6000 on localhost
